// =================================================
// =                                               =
// = Sound.Autogenerated.cs                        =
// =                                               =
// = AUTO-GENERATED FILE - Do not edit!            =
// =                                               =
// =================================================

using System.Collections.Generic;

namespace Tobo.Audio
{
    public partial class Sound
    {
        public enum ID
        {
            None = 0,
            SlotHover = -1850161273,
            UIClick = 1713459037,
            UIHover = 1718178577,
        }

        public static Sound SlotHover => Get(ID.SlotHover);
        public static Sound UIClick => Get(ID.UIClick);
        public static Sound UIHover => Get(ID.UIHover);

        internal static Dictionary<string, string> FilenameToSoundIDName { get; private set; } = new Dictionary<string, string>()
        {
        };

        internal static Dictionary<string, Sound.ID> SoundIDNameToSoundID { get; private set; } = new Dictionary<string, Sound.ID>()
        {
            { "None", Sound.ID.None },
            { "SlotHover", Sound.ID.SlotHover },
            { "UIClick", Sound.ID.UIClick },
            { "UIHover", Sound.ID.UIHover },
        };
    }
}

